export const equipmentLibrary = [
  {
    id: "olympic_barbell",
    name: "Olympic Barbell",
    image_url: "https://images.pexels.com/photos/703014/pexels-photo-703014.jpeg",
    category: "Bars & Plates",
  },
  {
    id: "ez_bar",
    name: "EZ Bar",
    image_url: "https://images.pexels.com/photos/11513151/pexels-photo-11513151.jpeg",
    category: "Bars & Plates",
  },
  {
    id: "landmine",
    name: "Landmine",
    image_url: "https://images.pexels.com/photos/27810159/pexels-photo-27810159.jpeg",
    category: "Attachments",
  },
  {
    id: "flat_bench",
    name: "Flat Bench",
    image_url: "https://images.pexels.com/photos/3839310/pexels-photo-3839310.jpeg",
    category: "Benches",
  },
  {
    id: "incline_bench",
    name: "Incline Bench",
    image_url: "https://images.pexels.com/photos/35986386/pexels-photo-35986386.jpeg",
    category: "Benches",
  },
  {
    id: "decline_bench",
    name: "Decline Bench",
    image_url: "https://images.pexels.com/photos/4162548/pexels-photo-4162548.jpeg",
    category: "Benches",
  },
  {
    id: "squat_rack",
    name: "Squat Rack",
    image_url: "https://images.pexels.com/photos/28636774/pexels-photo-28636774.png",
    category: "Racks",
  },
  {
    id: "smith_machine",
    name: "Smith Machine",
    image_url: "https://images.pexels.com/photos/5327525/pexels-photo-5327525.jpeg",
    category: "Machines",
  },
  {
    id: "preacher_curl_bench",
    name: "Preacher Curl Bench",
    image_url: "https://images.pexels.com/photos/14524650/pexels-photo-14524650.jpeg",
    category: "Benches",
  },
  {
    id: "pull_up_bar",
    name: "Pull Up Bar",
    image_url: "https://images.pexels.com/photos/14591610/pexels-photo-14591610.jpeg",
    category: "Bodyweight",
  },
  {
    id: "dumbbells",
    name: "Dumbbells",
    image_url: "https://images.pexels.com/photos/6550849/pexels-photo-6550849.jpeg",
    category: "Free Weights",
  },
  {
    id: "hack_squat_machine",
    name: "Hack Squat Machine",
    image_url: "https://unsplash.com/photos/a-man-sitting-on-a-bench-in-a-gym-C6fJDfsNJtE",
    category: "Machines",
  },
  {
    id: "leg_press_machine",
    name: "Leg Press Machine",
    image_url: "https://images.pexels.com/photos/3076512/pexels-photo-3076512.jpeg",
    category: "Machines",
  },
  {
    id: "chest_supported_row_machine",
    name: "Chest Supported Row Machine",
    image_url: "https://i.pinimg.com/originals/9b/20/f1/9b20f131d47aa767e132a78d7c942666.jpg",
    category: "Machines",
  },
  {
    id: "lat_pulldown_machine",
    name: "Lat Pulldown Machine",
    image_url: "https://images.pexels.com/photos/31329758/pexels-photo-31329758.jpeg",
    category: "Machines",
  },
  {
    id: "seated_leg_curl_machine",
    name: "Seated Leg Curl Machine",
    image_url: "https://images.pexels.com/photos/28731788/pexels-photo-28731788.jpeg",
    category: "Machines",
  },
  {
    id: "calf_extension_machine",
    name: "Calf Extension Machine",
    image_url: "https://images.pexels.com/photos/11191177/pexels-photo-11191177.jpeg",
    category: "Machines",
  },
  {
    id: "incline_chest_press_machine",
    name: "Incline Chest Press Machine",
    image_url: "https://images.pexels.com/photos/3888104/pexels-photo-3888104.jpeg",
    category: "Machines",
  },
  {
    id: "abductor_machine",
    name: "Abductor Machine",
    image_url: "https://images.pexels.com/photos/6539861/pexels-photo-6539861.jpeg",
    category: "Machines",
  },
  {
    id: "adductor_machine",
    name: "Adductor Machine",
    image_url: "https://tse2.mm.bing.net/th/id/OIP.a3FWhsGwQlfFezPc8VcJHgHaHa?pid=Api&h=220&P=0",
    category: "Machines",
  },
  {
    id: "fly_machine",
    name: "Fly Machine",
    image_url: "https://images.pexels.com/photos/14616295/pexels-photo-14616295.jpeg",
    category: "Machines",
  },
  {
    id: "leg_extension_machine",
    name: "Leg Extension Machine",
    image_url: "https://images.pexels.com/photos/19722966/pexels-photo-19722966.jpeg",
    category: "Machines",
  },
  {
    id: "preacher_curl_machine",
    name: "Preacher Curl Machine",
    image_url: "https://images.pexels.com/photos/14524650/pexels-photo-14524650.jpeg",
    category: "Machines",
  },
  {
    id: "lateral_raise_machine",
    name: "Lateral Raise Machine",
    image_url: "https://images.pexels.com/photos/5327460/pexels-photo-5327460.jpeg",
    category: "Machines",
  },
  {
    id: "row_machine",
    name: "Row Machine",
    image_url: "https://images.pexels.com/photos/6389080/pexels-photo-6389080.jpeg",
    category: "Machines",
  },
  {
    id: "crossover_cable",
    name: "Crossover Cable",
    image_url: "https://images.pexels.com/photos/5327505/pexels-photo-5327505.jpeg",
    category: "Cable Systems",
  },
  {
    id: "hi_lo_pull_cable",
    name: "Hi Lo Pull Cable",
    image_url: "https://images.pexels.com/photos/33185466/pexels-photo-33185466.jpeg",
    category: "Cable Systems",
  },
  {
    id: "lat_pulldown_cable",
    name: "Lat Pulldown Cable",
    image_url: "https://images.pexels.com/photos/29218860/pexels-photo-29218860.jpeg",
    category: "Cable Systems",
  },
  {
    id: "row_cable",
    name: "Row Cable",
    image_url: "https://images.pexels.com/photos/4162481/pexels-photo-4162481.jpeg",
    category: "Cable Systems",
  },
  {
    id: "ab_wheel",
    name: "Ab Wheel",
    image_url: "https://images.pexels.com/photos/8032833/pexels-photo-8032833.jpeg",
    category: "Accessories",
  },
  {
    id: "stability_ball",
    name: "Stability Ball",
    image_url: "https://images.pexels.com/photos/4587677/pexels-photo-4587677.jpeg",
    category: "Accessories",
  },
  {
    id: "foam_roller",
    name: "Foam Roller",
    image_url: "https://images.pexels.com/photos/4587697/pexels-photo-4587697.jpeg",
    category: "Recovery",
  },
  {
    id: "trx",
    name: "TRX",
    image_url: "https://images.pexels.com/photos/12905815/pexels-photo-12905815.jpeg",
    category: "Suspension Training",
  },
  {
    id: "tire",
    name: "Workout Tire",
    image_url: "https://images.pexels.com/photos/4720833/pexels-photo-4720833.jpeg",
    category: "Functional Training",
  },
  {
    id: "sissy_squat_machine",
    name: "Sissy Squat Machine",
    image_url: "https://images.pexels.com/photos/11191169/pexels-photo-11191169.jpeg",
    category: "Machines",
  },
  {
    id: "battle_ropes",
    name: "Battle Ropes",
    image_url: "https://images.pexels.com/photos/7652096/pexels-photo-7652096.jpeg",
    category: "Functional Training",
  },
  {
    id: "loop_bands",
    name: "Loop Bands",
    image_url: "https://images.pexels.com/photos/7479770/pexels-photo-7479770.jpeg",
    category: "Accessories",
  },
];

export function getEquipmentById(id) {
  return equipmentLibrary.find(equipment => equipment.id === id);
}