import { Link } from "react-router-dom";
import { Dumbbell, Sparkles, Users, LineChart, Mail } from "lucide-react";
import {
  Button,
  Container,
  Title,
  Text,
  Group,
  Box,
  Stack,
  ThemeIcon,
  SimpleGrid,
  Paper,
  rem,
  Flex,
} from "@mantine/core";
import { notifications } from "@mantine/notifications";
import { supabase } from "@/lib/supabase";
import { ThemeToggle } from "@/components/theme-toggle";

export default function LandingPage() {
  const handleGoogleLogin = async () => {
    const { error } = await supabase.auth.signInWithOAuth({
      provider: "google",
      options: { redirectTo: window.location.origin + "/dashboard" },
    });

    if (error) {
      console.error("Google Auth error:", error.message);
      notifications.show({
        title: "Authentication failed",
        message: error.message,
        color: "red",
      });
    }
  };

  return (
    <Box
      className="bg-hero"
      style={{
        minHeight: "100vh",
        position: "relative",
        overflow: "hidden",
        display: "flex",
        flexDirection: "column",
      }}
    >
      {/* Header */}
      <Box
        component="header"
        style={{ position: "relative", zIndex: 10, flexShrink: 0 }}
      >
        <Container size="lg" px="md">
          <Group justify="space-between" h={rem(80)}>
            <Group gap="xs">
              <ThemeIcon variant="light" size="lg" radius="xl">
                <Dumbbell size={20} />
              </ThemeIcon>
              <Text size="lg" fw={700} style={{ letterSpacing: "-0.02em" }}>
                FitBae
              </Text>
            </Group>
            <ThemeToggle />
          </Group>
        </Container>
      </Box>

      <Container
        size="lg"
        px="md"
        style={{ flex: 1, display: "flex", alignItems: "center" }}
      >
        <Flex
          direction="column"
          align="center"
          justify="center"
          w="100%"
          py={64}
          style={{ position: "relative", zIndex: 10, minHeight: "100%" }}
        >
          {/* AI Badge */}
          <Group
            gap={6}
            px={12}
            py={4}
            style={{
              backgroundColor: "var(--mantine-color-primary-light)",
              color: "var(--mantine-color-primary-filled)",
              borderRadius: rem(100),
              border: "1px solid var(--mantine-color-primary-light-hover)",
            }}
          >
            <Sparkles size={14} />
            <Text size="xs" fw={700} tt="uppercase">
              Powered by AI
            </Text>
          </Group>

          {/* Main Hero Card */}
          <Paper
            className="glass shadow-glow"
            radius="32px"
            p={{ base: "xl", md: 48 }}
            mt={24}
            style={{ maxWidth: rem(600), width: "100%" }}
          >
            <Stack gap="lg" align="center">
              <Title
                ta="center"
                order={1}
                size={rem(48)}
                fw={800}
                style={{ lineHeight: 1.1 }}
              >
                Your <span className="text-gradient">AI-Powered</span> Workout
                Partner
              </Title>
              <Text c="dimmed" ta="center" size="lg">
                Personalized workout plans generated by AI, built around your
                goals and equipment.
              </Text>

              <Stack gap="sm" w="100%" mt="md">
                <Button
                  onClick={handleGoogleLogin}
                  size="lg"
                  radius="xl"
                  variant="white"
                  color="dark"
                  leftSection={<GoogleIcon />}
                  fullWidth
                  fw={600}
                >
                  Sign in with Google
                </Button>
                <Button
                  component={Link}
                  to="/onboarding"
                  variant="subtle"
                  color="gray"
                  leftSection={<Mail size={16} />}
                  fullWidth
                >
                  Sign in with email
                </Button>
              </Stack>
            </Stack>
          </Paper>

          {/* Features Grid */}
          <SimpleGrid
            cols={{ base: 1, md: 3 }}
            spacing="md"
            mt={64}
            w="100%"
            style={{ maxWidth: rem(800) }}
          >
            <Feature
              icon={<Sparkles size={20} />}
              title="AI-Generated Plans"
              desc="Tailored to your goals"
            />
            <Feature
              icon={<Users size={20} />}
              title="Multi-User Profiles"
              desc="One app, whole family"
            />
            <Feature
              icon={<LineChart size={20} />}
              title="Track Your Progress"
              desc="See every PR you hit"
            />
          </SimpleGrid>
        </Flex>
      </Container>
    </Box>
  );
}

function Feature({ icon, title, desc }) {
  return (
    <Group wrap="nowrap" className="glass" p="md" radius="xl" gap="md">
      <ThemeIcon
        variant="light"
        size={rem(40)}
        radius="md"
        style={{ flexShrink: 0 }}
      >
        {icon}
      </ThemeIcon>
      <Box>
        <Text size="sm" fw={700}>
          {title}
        </Text>
        <Text c="dimmed" size="xs">
          {desc}
        </Text>
      </Box>
    </Group>
  );
}

function GoogleIcon() {
  return (
    <svg width="18" height="18" viewBox="0 0 24 24">
      <path
        fill="#4285F4"
        d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"
      />
      <path
        fill="#34A853"
        d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.99.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"
      />
      <path
        fill="#FBBC05"
        d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"
      />
      <path
        fill="#EA4335"
        d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"
      />
    </svg>
  );
}
